version: '3'

services:
  carsdb:
    image: postgres
    ports:
      - "5436:80"
  web:
    build: .
    command: bash -c "python manage.py makemigrations &&  python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8003:8000"
    depends_on:
      - carsdb
