# Generated by Django 2.1.2 on 2018-11-16 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='id_token',
            field=models.BigIntegerField(),
        ),
    ]
