# Generated by Django 2.1.2 on 2018-11-16 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20181116_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='document',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
