# Generated by Django 2.1.2 on 2018-11-16 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_notificationsimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NotificationsImage',
            new_name='Document',
        ),
    ]
