# Generated by Django 2.1.2 on 2018-11-16 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_auto_20181116_1159'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Document',
            new_name='Documents',
        ),
    ]
