# Generated by Django 2.1.2 on 2018-11-16 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_auto_20181116_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='id_token',
            field=models.BigIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='plate',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
