# Generated by Django 2.1.2 on 2018-11-16 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_auto_20181116_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='id_token',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='plate',
            field=models.CharField(max_length=8),
        ),
    ]
